brunoos/luasec

src/x509.c
Calling `x509cert:extensions()` on a certificate containing iPAddress SANs will return those IP addresses as raw bytes.
Additionally, if combined with `x509cert:setencode("utf8")`, the `ASN1_STRING_to_UTF8()` call will fail and nothing will be pushed.
The first first 3 commits fixes issues by returning nil instead of something invalid. The last commit uses `inet_ntop()` to convert IP addresses to the common string form.
=> iPAddress encoding

src/luasocket/Makefile
On Exherbo, ar is prefixed by the target triple.
=> Do not hardcode ar

luasec-0.6alpha-1.rockspec
For the LuaRocks versioning algorithm, `0.6a` > `0.6`, but `0.6alpha` < `0.6`. It recognizes `alpha` < `beta` < `rc`, but other letter suffixes are recognized as greater than numbers (e.g. `1.0k` > `1.0g` > `1.0`).
=> Rename 0.6a to 0.6alpha

src/context.c
SSLv3 support was disabled in LibreSSL. 
This change guards the SSLv3_method() with OPENSSL_NO_SSL3, so fix build with LibreSSL.
=> guard SSLv3_method() with #ifndef OPENSSL_NO_SSL3

luasec-0.6alpha-3.rockspec
A patch is added to the rockspec to fix an issue in the interaction between LuaRocks and Microsoft compilers.
LuaRocks build backend assumes the library being built will always export a symbol called "luaopen_<library name>". This is not the case with LuaSec so it fails to link.
The patch just adds an empty implementation of that, so it will properly link.
refs #37
=> Enables building with LuaRocks and MS compilers

src/x509.c
This lets you check if one certificate was issued by another one.
> print(parent:issued(child))
true
The backing OpenSSL function is undocumented and I believe that it performs only issuer name matching and signature verification.  E.g. Basic Constraints seem to be ignored.
I needed this for doing DANE-TA (usage 2) as part of my DANE implementation for Prosody.
Thoughts?  I'm not sure this is ready for merging, so I would like some feedback on if this is something useful.
=> Method for checking if one certificate issued another

src/ssl.c
The number of bytes received by ssl_recv() is being passed to luaL_addlstring() (in recvall()) but it was being left either uninitialized or being set to an error code.  The crashing case I found was when the state was not LSEC_STATE_CONNECTED and ssl_recv() returned immediately without setting "got".
=> Fix crash after dohandshake() fails

samples/README, samples/certs/clientA.cnf, samples/certs/clientB.cnf, samples/certs/rootA.cnf, samples/certs/rootB.cnf, samples/certs/serverA.cnf, samples/certs/serverB.cnf, src/luasocket/buffer.c, src/luasocket/io.h, src/luasocket/socket.h, src/luasocket/timeout.h, src/luasocket/usocket.c, src/options.lua, src/x509.c
fixes for spelling issues (just in source comments, .. ) as seen on:
https://lintian.debian.org/full/gareuselesinge@debian.org.html#lua-sec_0.5.1-1
=> spelling fixes, as seen on lintian.debian.org

samples/luaossl/client.lua, samples/luaossl/server.lua, src/ssl.c
This allows a user to create an `SSL_CTX*` via [luaossl](https://github.com/wahern/luaossl/) and then pass it across to luasec.
=> Allow passing a luaossl context for socket creation/wrapping

src/ssl.c
This is necessary for cross-compilation of Windows binaries on non-Windows
platforms (and harmless for Windows).
Can this still make it to 0.7? :)
=> Use lowercase Windows header name

samples/certs/all.sh, samples/certs/clientA.sh, samples/certs/clientB.sh, samples/certs/rootA.sh, samples/certs/rootB.sh, samples/certs/serverA.cnf, samples/certs/serverA.sh, samples/certs/serverB.cnf, samples/certs/serverB.sh
- Use 2048 bit keys (required for modern OpenSSL)
- Use SHA256 instead of SHA1 (required for modern OpenSSL)
- Add a SubjectAltName to be able to trigger certain edge-cases
- Add all.sh to conveniently re-generate certificates
=> Modernize certificate generation

samples/loop/client.lua, src/x509.c
``X509V3_EXT_d2i`` allocates a thing which needs to be freed. I added the free call.
To reproduce, you’ll need the patches from this branch as well as #124, because it only happens when the certificate has a Subject Alternative Name extension (which is probably why it wasn’t caught in the normal loop testing yet).
You can reproduce the memory leak  by applying only #124 and 0775d57 and then run the loop client under ``valgrind --leak-check=full lua ./client.lua`` (it takes a while to start up).
Let it run for a few iterations and then abort it with Ctrl+C. Valgrind will show a leak like this:
```
==5623== 720 (192 direct, 528 indirect) bytes in 6 blocks are definitely lost in loss record 8 of 10
==5623==    at 0x48357BF: malloc (vg_replace_malloc.c:299)
==5623==    by 0x5710CE8: …
```
=> Fix memory leak in meth_extensions

src/https.lua
Exposing the `tcp()` function would allow LuaSocket HTTPS redirects to succeed transparently without the caller having to provide a separate socket creation function. Also allows normal HTTP or HTTPS requests via the same call. See also [diegonehab/luasocket:#268](https://github.com/diegonehab/luasocket/pull/268).
=> Expose tcp() for use by LuaSocket

samples/multicert/client.lua, samples/multicert/server.lua, src/ssl.lua
This allows a context to be set up with multiple certificates. This is done similarly to using a single certificate in existing branches, except that the property names in the `cfg` table are pluralized and are passed as tables with matching keys rather than as three individual strings.
Backwards-compatibility is achieved by wrapping the individual strings in tables if they are passed in that manner.
This fixes #27
=> Enable multiple SSL certificates

src/x509.c
Similar to #125.
To reproduce:
```lua
cert = require"ssl".loadcertificate(io.open("example.crt"):read("*a"))
cert:extensions()
```
Thanks to @zeen for identifying and @horazont for providing test
environment.
=> Fix general_name leak in cert:extensions()

samples/dane/client.lua, src/context.c, src/ssl.c, src/ssl.lua
This exposes OpenSSL methods available for [DANE](https://en.wikipedia.org/wiki/DNS-based_Authentication_of_Named_Entities). The included example uses [luaunbound](http://luarocks.org/modules/zash/luaunbound).
=> DANE support

src/ssl.c
winsock define INVALID_SOCKET as (UINT_PTR)(~0)
in win64 it is 0xffffffffffffffff
if pushed by lua_pushnumber, then ssl.core.SOCKET_INVALID is 1.84467440737096E19
tested in win32/64, linux32/64 lua5.1 and lua5.3
=> SOCKET_INVALID pushed as integer, not as number

src/ssl.c
Either intentionaly or due to bug in openssl in some marginal
cases SSL_send reports SYSCALL error whilst errno is set to 0.
This either could mean that SSL_send did not made any system
call or errno were prematurely reset with consequent syscalls.
And in consequence sendraw() is not propagated with correct
errno ends up in infinite loop trying to send same data.
Such behaviour was usually observed after third consequential
failed SSL send attempt which application was not aware of.
First send failed with syscall errno 32 (Broken pipe) second
one with SSL error 0x1409e10f (bad length) and lastly next
send attemt results with SYSCALL error and errno 0.
Tested using:
* OpenSSL v1.1.1
* musl v1.1.20 (c50985d5c8e316c5c464f352e79eeebfed1121a9)
* Linux 4.4.60+yocto armv7l
=> Handle SSL_send SYSCALL error without errno

src/x509.c
This should be a backwards compatible fix as the exported name is already spelt correctly.
=> Fix meth_get_{sinagure => signature}_name function name

src/config.c, src/context.c, src/ssl.lua
The only flag at the moment is one that disables name checks, which is
needed for certain protocols such as XMPP.
API comments welcome.
Sorry I missed this in #122 
```lua
local conn = ssl.wrap(socket.connect(host, port), {
mode = "client",
... -- other settings etc
dane = { "no_ee_namechecks" }
})
conn:setdane(host); -- still need the host, but its value is ignored
conn:settlsa(3, 1, 1, hex"deadbeef..."))
conn:dohandshake()
```
=> Support passing DANE flags

src/ssl.c
Binds [`SSL_export_keying_material()`](https://www.openssl.org/docs/manmaster/man3/SSL_export_keying_material.html) which is used for things like [SASL channel binding](https://datatracker.ietf.org/doc/draft-ietf-kitten-tls-channel-bindings-for-tls13/).
=> Add key material export method

src/x509.c
* The commit https://github.com/brunoos/luasec/commit/de393417b7c7566caf1e0a0ad54132942ac4f049 introduces high dependency due raices requirement to openssl 1.1.0l+
* The X509_REQ_get0_signature(), X509_REQ_get_signature_nid(), X509_CRL_get0_signature() and X509_CRL_get_signature_nid() were added in OpenSSL 1.1.0.
* This patch makes luasec runs on all kind of embebed systems that cannot be upgraded due vendors limitations
=> backguard compat for openssl on providers, like LTS linuxes

samples/chain/server.lua, src/ssl.c
These methods mirror the existing methods that fetch the peer certificate and chain. Due to various factors (SNI, multiple key types, etc.) it is not always trivial for an application to determine what certificate was presented to the client. However there are various use-cases where this is needed, such as tls-server-end-point channel binding and OCSP stapling.
Requires OpenSSL 1.0.2+ (note: SSL_get_certificate() has existed for a very long time, but was lacking documentation until OpenSSL 3.0).
=> ssl: Add :getlocalchain() + :getlocalcertificate() to mirror peer methods

src/luasocket/usocket.c
Some systems have no `EAI_OVERFLOW`, in particular macOS <= 10.5, as well as early versions of 10.6.
Protect it with the macro, in the same way as it is done below for `EAI_PROTOCOL`.
=> usocket.c: place EAI_OVERFLOW inside macro, unbreak build on <10.7

src/compat.h, src/ssl.c
Encountered the bug in #172 after upgrading to OpenSSL 3.0.9, so it appears to still be present.
Occurs when writing to a connection that has been closed by the remote.
=> Expand workaround for zero errno to OpenSSL 3.0.x
